<?php
global $wpdb, $LIONSCRIPTS;
define('LIONSCRIPTS_WIB_BASIC_WEB_HOME_PAGE_NAME_SHORT', 'LionScripts');
define('LIONSCRIPTS_WIB_BASIC_FULL_NAME', 'IP Address Blocker');
define('LIONSCRIPTS_WIB_BASIC_FULL_NAME_2', 'IP Blocker');
define('LIONSCRIPTS_WIB_BASIC_WEB_HOME_PAGE_NAME', LIONSCRIPTS_WIB_BASIC_WEB_HOME_PAGE_NAME_SHORT.'.com');
define('LIONSCRIPTS_WIB_BASIC_FULL_HOME_PAGE_LINK', 'http://www.'.strtolower(LIONSCRIPTS_WIB_BASIC_WEB_HOME_PAGE_NAME).'/');
define('LIONSCRIPTS_WIB_BASIC_URL_NAME', str_replace(' ', '-', strtolower(LIONSCRIPTS_WIB_BASIC_FULL_NAME)));
define('LIONSCRIPTS_WIB_BASIC_FULL_PAGE_LINK', 'http://www.lionscripts.com/product/wordpress-ip-address-blocker-pro/');
define('LIONSCRIPTS_WIB_BASIC_FULL_NAME_PRO', LIONSCRIPTS_WIB_BASIC_FULL_NAME_2.' Pro');
define('LIONSCRIPTS_WIB_BASIC_FULL_NAME_HEADING', 'LionScripts: '.LIONSCRIPTS_WIB_BASIC_FULL_NAME_2.' Lite');
define('LIONSCRIPTS_WIB_BASIC_SHORT_NAME', LIONSCRIPTS_WIB_BASIC_FULL_NAME);
define('LIONSCRIPTS_WIB_BASIC_TABLE_NAME', strtolower(LIONSCRIPTS_WIB_BASIC_WEB_HOME_PAGE_NAME_SHORT).'_'.str_replace(' ', '_', strtolower(LIONSCRIPTS_WIB_BASIC_FULL_NAME)));
define('LIONSCRIPTS_WIB_BASIC_TABLE_NAME_OPTIONS', LIONSCRIPTS_WIB_BASIC_TABLE_NAME."_options");
define('LIONSCRIPTS_WIB_BASIC_BASE', get_bloginfo('wpurl')."/wp-content/plugins/".basename(dirname(__FILE__)));
define('LIONSCRIPTS_WIB_ADMIN_URL', get_admin_url()."admin.php?page=".basename(dirname(__FILE__)));
define('LIONSCRIPTS_WIB_BASIC_ASSETS', LIONSCRIPTS_WIB_BASIC_BASE.'/assets');
define('LIONSCRIPTS_WIB_BASIC_DB_VERSION', '4.0');
define('LIONSCRIPTS_WIB_BASIC_SUPPORT_WEBSITE', 'support.'.strtolower(LIONSCRIPTS_WIB_BASIC_WEB_HOME_PAGE_NAME));
define('LIONSCRIPTS_WIB_BASIC_FACEBOOK_LINK', "http://www.facebook.com/".LIONSCRIPTS_WIB_BASIC_WEB_HOME_PAGE_NAME_SHORT);
define('LIONSCRIPTS_WIB_BASIC_TWITTER_LINK', 'http://twitter.com/'.LIONSCRIPTS_WIB_BASIC_WEB_HOME_PAGE_NAME_SHORT);
if (!empty($_SERVER['HTTP_CLIENT_IP']))
    $ip = $_SERVER['HTTP_CLIENT_IP'];
elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR']))
    $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
else
    $ip = $_SERVER['REMOTE_ADDR'];
define('LIONSCRIPTS_WIB_BASIC_CURRENT_USER_IP', $ip);
define('LIONSCRIPTS_WIB_BASIC_ATTRIB', '<font style="font-size:12px;"><center>IP Blocking Protection is enabled by <a href="'.LIONSCRIPTS_WIB_BASIC_FULL_PAGE_LINK.'" target="_blank">'.LIONSCRIPTS_WIB_BASIC_FULL_NAME.'</a> from <a href="'.LIONSCRIPTS_WIB_BASIC_FULL_HOME_PAGE_LINK.'" target="_blank">'.LIONSCRIPTS_WIB_BASIC_WEB_HOME_PAGE_NAME.'</a>.</center></font>');
?>